### ISSUE TITLE
Retrieve SDSS velocity dispersion?

### ISSUE THREAD

**Issue by kvgc** [astro-datalab/sparclclient#22]
Hi,
is there a way to retrieve the SDSS velocity dispersion using sparclclient using the retrieve_by_specid method? 

```
# Define the fields to include in the retrieve function (would like to also add the velocity dispersion measured here)
inc = ['id', 'specid', 'data_release', 'redshift', 'redshift_err', 'flux', 'wavelength', 'model', 'ivar', 'mask', 'spectype']


results_II = client.retrieve_by_specid(
                                specid_list=[f['specid'] for f in found_I.records],
                                include=inc,
                                dataset_list=['SDSS-DR16','BOSS-DR16']
)

```
Thanks!
--
kvgc

**Comment by jacquesalice** [comment]
Hi @kvgc thanks for your message. We are working on a way to include more fields such as velocity dispersion that can be retrieved with SPARCL. In the meantime, you can use Astro Data Lab to query the sdss_dr16.specobj table (table info [here](https://datalab.noirlab.edu/query.php?name=sdss_dr16.specobj)) to find velocity dispersion (veldisp) for specific specobjids passed to it. Here is what that would look like:

If you don't already have Astro Data Lab installed, you can pip install it:
```
pip install --ignore-installed --no-cache-dir astro-datalab
```
Then import the queryClient:
```
from dl import queryClient as qc
```
Given a list of specids (specobjids) like this: 
```
specids = [6988698046080241664,
           6971782884823945216,
          -7847473560484032512,
           8023302759209259008,
          -8466723469246836736,
           4160448457977647104]
```
Write the query statement and pass the specids:
```
q = (f"""SELECT specobjid, veldisp FROM sdss_dr16.specobj
         WHERE specobjid IN ({str(specids)[1:-1]})
     """)
```
Submit to Astro Data Lab's queryClient, output as Pandas Dataframe:
```
re = qc.query(sql=q,fmt='pandas')
```

Hope that helps. Let us know if you have any more questions

**Comment by kvgc** [comment]
Hi @jacquesalice 
Thank you so much!
--
kvgc
